project:
  type: book
  output-dir: docs

book:
  title: "Estudio panel Educaci√≥n y Meritocracia"
  author: "Equipo Edumer"
#  date: "22-05-2024"
  chapters:
    - index.qmd
    - intro.qmd
    - reporte_metodologico.qmd
    - meritocracia.qmd
    - ciudadania.qmd
    - references.qmd

bibliography: Educacion-meritocracia.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

